- ros_topic_name: camera_5/color/camera_info
  gz_topic_name: /cpr_generic_e/sensors/camera_5/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera_5/points
  gz_topic_name: /cpr_generic_e/sensors/camera_5/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera_5/depth/camera_info
  gz_topic_name: /cpr_generic_e/sensors/camera_5/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
